export const ALL_PURPOSE_TECHNIQUES = [
  "ES01 Glorify People",
  "ES02 Honour a Place",
  "ES03 Get Behind an Attitude",
  "ES04 Elevate an Object",
  "ES05 Celebrate a Journey",
  "ES06 Cherish a Moment",
  "ES07 Empathise and Support",
  "ES08 Dramatise the Problem",
  "ES09 Dramatise the Solution",
  "ES10 Use an Analogy for the Problem",
  "ES11 Use an Analogy for the Solution",
  "ES12 Humanise",
  "ES13 Compare and Contrast",
  "ES14 Rename, Redefine, Reclassify",
  "ES15 Invite the Audience Backstage",
  "ES16 Hire a Surprising Endorser",
  "ES17 Transport Them to Other Worlds",
  "ES18 Stand Up for the Little Guy",
  "ES19 Invent a Mascot",
  "ES20 Debunk a Stereotype",
  "ES21 Conduct an Experiment"
];
